# Generated by Django 4.1.8 on 2023-04-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeetName', models.CharField(max_length=250)),
                ('Department', models.CharField(max_length=250)),
                ('DateOfJoining', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=250)),
            ],
        ),
    ]
